# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\msys64\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\msys64\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\umarp\Downloads\turbo-racers-pro\turbo-racers-pro

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\umarp\Downloads\turbo-racers-pro\turbo-racers-pro\build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	C:\msys64\mingw64\bin\cpack.exe --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	C:\msys64\mingw64\bin\cpack.exe --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\msys64\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\msys64\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	C:\msys64\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	C:\msys64\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	C:\msys64\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\umarp\Downloads\turbo-racers-pro\turbo-racers-pro\build\CMakeFiles C:\Users\umarp\Downloads\turbo-racers-pro\turbo-racers-pro\build\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\umarp\Downloads\turbo-racers-pro\turbo-racers-pro\build\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TurboRacers

# Build rule for target.
TurboRacers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 TurboRacers
.PHONY : TurboRacers

# fast build rule for target.
TurboRacers/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/build
.PHONY : TurboRacers/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps\raylib-build\CMakeFiles\uninstall.dir\build.make _deps/raylib-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps\raylib-build\raylib\CMakeFiles\raylib.dir\build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps\raylib-build\raylib\external\glfw\src\CMakeFiles\glfw.dir\build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps\raylib-build\raylib\external\glfw\src\CMakeFiles\update_mappings.dir\build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/Audio.obj: src/Audio.cpp.obj
.PHONY : src/Audio.obj

# target to build an object file
src/Audio.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Audio.cpp.obj
.PHONY : src/Audio.cpp.obj

src/Audio.i: src/Audio.cpp.i
.PHONY : src/Audio.i

# target to preprocess a source file
src/Audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Audio.cpp.i
.PHONY : src/Audio.cpp.i

src/Audio.s: src/Audio.cpp.s
.PHONY : src/Audio.s

# target to generate assembly for a file
src/Audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Audio.cpp.s
.PHONY : src/Audio.cpp.s

src/Car.obj: src/Car.cpp.obj
.PHONY : src/Car.obj

# target to build an object file
src/Car.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Car.cpp.obj
.PHONY : src/Car.cpp.obj

src/Car.i: src/Car.cpp.i
.PHONY : src/Car.i

# target to preprocess a source file
src/Car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Car.cpp.i
.PHONY : src/Car.cpp.i

src/Car.s: src/Car.cpp.s
.PHONY : src/Car.s

# target to generate assembly for a file
src/Car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Car.cpp.s
.PHONY : src/Car.cpp.s

src/Game.obj: src/Game.cpp.obj
.PHONY : src/Game.obj

# target to build an object file
src/Game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Game.cpp.obj
.PHONY : src/Game.cpp.obj

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Menu.obj: src/Menu.cpp.obj
.PHONY : src/Menu.obj

# target to build an object file
src/Menu.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Menu.cpp.obj
.PHONY : src/Menu.cpp.obj

src/Menu.i: src/Menu.cpp.i
.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s
.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Track.obj: src/Track.cpp.obj
.PHONY : src/Track.obj

# target to build an object file
src/Track.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Track.cpp.obj
.PHONY : src/Track.cpp.obj

src/Track.i: src/Track.cpp.i
.PHONY : src/Track.i

# target to preprocess a source file
src/Track.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Track.cpp.i
.PHONY : src/Track.cpp.i

src/Track.s: src/Track.cpp.s
.PHONY : src/Track.s

# target to generate assembly for a file
src/Track.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/Track.cpp.s
.PHONY : src/Track.cpp.s

src/TrackFactory.obj: src/TrackFactory.cpp.obj
.PHONY : src/TrackFactory.obj

# target to build an object file
src/TrackFactory.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/TrackFactory.cpp.obj
.PHONY : src/TrackFactory.cpp.obj

src/TrackFactory.i: src/TrackFactory.cpp.i
.PHONY : src/TrackFactory.i

# target to preprocess a source file
src/TrackFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/TrackFactory.cpp.i
.PHONY : src/TrackFactory.cpp.i

src/TrackFactory.s: src/TrackFactory.cpp.s
.PHONY : src/TrackFactory.s

# target to generate assembly for a file
src/TrackFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/TrackFactory.cpp.s
.PHONY : src/TrackFactory.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TurboRacers.dir\build.make CMakeFiles/TurboRacers.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... uninstall
	@echo ... update_mappings
	@echo ... TurboRacers
	@echo ... glfw
	@echo ... raylib
	@echo ... src/Audio.obj
	@echo ... src/Audio.i
	@echo ... src/Audio.s
	@echo ... src/Car.obj
	@echo ... src/Car.i
	@echo ... src/Car.s
	@echo ... src/Game.obj
	@echo ... src/Game.i
	@echo ... src/Game.s
	@echo ... src/Menu.obj
	@echo ... src/Menu.i
	@echo ... src/Menu.s
	@echo ... src/Track.obj
	@echo ... src/Track.i
	@echo ... src/Track.s
	@echo ... src/TrackFactory.obj
	@echo ... src/TrackFactory.i
	@echo ... src/TrackFactory.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

